import './globals.css'
import '../fonts/Inter-3.19/Inter Web/inter.css'


import { cookies } from 'next/headers'
import Wrapper from "../components/Nav/wrapper";
import { useRouter } from 'next/navigation';
import { CookiesProvider } from 'next-client-cookies/server';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {

  const cookieStore = cookies()
  const cToken = cookieStore.get('token')

  return (
    <html style={{
      overflow: "hidden", fontFamily: "Inter"
    }} lang="en">

      <body suppressHydrationWarning style={{ fontFamily: "inherit", height: "100vh", width: "100vw", overflow: "auto", display: "flex" }}>
<<<<<<< HEAD
        <CookiesProvider>
          <Wrapper token={cToken}>{children}</Wrapper>
        </CookiesProvider>
=======
<CookiesProvider>
        <Wrapper token={cToken}>{children}</Wrapper>
</CookiesProvider>
>>>>>>> 8d4e3f9d762a13b4997f5e7d363043262b8aa1d5

      </body>
    </html>
  )
}
